server:
  port: 80

spring:
  application:
    name: csrftest


  datasource:
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csrft-learn

  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml



