spring:
  redis:
    host: llynsyw.cn
    port: 6379
    password: qwe123
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms